export const PRODUCTS_BY_CATEGORY_REQUEST = "PRODUCTS_BY_CATEGORY_REQUEST";
export const PRODUCTS_BY_CATEGORY_SUCCESS = "PRODUCTS_BY_CATEGORY_SUCCESS";
export const PRODUCTS_BY_CATEGORY_FAIL = "PRODUCTS_BY_CATEGORY_FAIL";
export const PRODUCTS_BY_CATEGORY_RESET = "PRODUCTS_BY_CATEGORY_RESET";
